import {
  Controller,
  Post,
  Get,
  Delete,
  Body,
  Param,
  Query,
  Res,
  NotFoundException,
  Logger,
} from '@nestjs/common';
import { Response } from 'express';
import { ApiTags, ApiOperation, ApiResponse, ApiQuery, ApiBody } from '@nestjs/swagger';
import { ResearchService } from './research.service';
import { CreateResearchDto } from './dto/create-research.dto';
import { ResearchQueryDto } from './dto/research-query.dto';
import { SourceQueryDto } from './dto/source-query.dto';
import { ResearchEventsService } from '../events/research-events.service';

@ApiTags('research')
@Controller('research')
export class ResearchController {
  private readonly logger = new Logger(ResearchController.name);

  constructor(
    private readonly researchService: ResearchService,
    private readonly eventsService: ResearchEventsService,
  ) {}

  @Post()
  @ApiOperation({ summary: 'Create a new research session' })
  @ApiResponse({ status: 201, description: 'Research session created and queued' })
  @ApiBody({ type: CreateResearchDto })
  async createResearch(@Body() dto: CreateResearchDto) {
    const result = await this.researchService.createResearch(dto);
    return { success: true, data: result };
  }

  @Get()
  @ApiOperation({ summary: 'Get research history with pagination' })
  @ApiQuery({ name: 'page', required: false, type: Number })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiQuery({ name: 'status', required: false, type: String })
  @ApiQuery({ name: 'search', required: false, type: String })
  async getResearchHistory(@Query() query: ResearchQueryDto) {
    const result = await this.researchService.getResearchHistory(query);
    return { success: true, ...result };
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get research session by ID' })
  @ApiResponse({ status: 200, description: 'Research session details' })
  async getResearch(@Param('id') id: string) {
    const session = await this.researchService.getResearch(id);
    if (!session) {
      throw new NotFoundException('Research session not found');
    }
    return { success: true, data: session };
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Delete research session and associated data' })
  @ApiResponse({ status: 200, description: 'Research session deleted' })
  async deleteResearch(@Param('id') id: string) {
    await this.researchService.deleteResearch(id);
    return { success: true, message: 'Research session deleted' };
  }

  @Get(':id/plan')
  @ApiOperation({ summary: 'Get the research plan generated by the Planner Agent' })
  async getResearchPlan(@Param('id') id: string) {
    const plan = await this.researchService.getResearchPlan(id);
    if (!plan) {
      throw new NotFoundException('Research session not found');
    }
    return { success: true, data: plan };
  }

  @Get(':id/sources')
  @ApiOperation({ summary: 'Get sources collected for a research session' })
  async getResearchSources(@Param('id') id: string, @Query() query: SourceQueryDto) {
    const result = await this.researchService.getResearchSources(id, query);
    return { success: true, ...result };
  }

  @Get(':id/stream')
  @ApiOperation({ summary: 'SSE stream of research progress events' })
  async streamResearch(@Param('id') id: string, @Res() res: Response) {
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no');
    res.flushHeaders();

    const recentEvents = this.eventsService.getRecentEvents(id);
    for (const evt of recentEvents) {
      res.write(`event: ${evt.event}\n`);
      res.write(`data: ${JSON.stringify(evt)}\n\n`);
    }

    const unsubscribe = this.eventsService.subscribe(id, (evt) => {
      res.write(`event: ${evt.event}\n`);
      res.write(`data: ${JSON.stringify(evt)}\n\n`);
    });

    const keepAlive = setInterval(() => {
      res.write(': keepalive\n\n');
    }, 15000);

    res.on('close', () => {
      clearInterval(keepAlive);
      unsubscribe();
    });
  }
}
