import {
  Controller,
  Post,
  Get,
  Delete,
  Body,
  Param,
  Query,
  Res,
  NotFoundException,
  Logger,
  Req,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiQuery, ApiBody } from '@nestjs/swagger';
import { ResearchService } from './research.service';
import { CreateResearchDto } from './dto/create-research.dto';
import { ResearchQueryDto } from './dto/research-query.dto';
import { SourceQueryDto } from './dto/source-query.dto';
import { ResearchEventsService } from '../events/research-events.service';
import { ResearchProgressEvent } from '@/common/interfaces/research.interface';
import { Request, Response } from 'express';

@ApiTags('research')
@Controller('research')
export class ResearchController {
  private readonly logger = new Logger(ResearchController.name);

  constructor(
    private readonly researchService: ResearchService,
    private readonly eventsService: ResearchEventsService,
  ) { }

  @Post()
  @ApiOperation({ summary: 'Create a new research session' })
  @ApiResponse({ status: 201, description: 'Research session created and queued' })
  @ApiBody({ type: CreateResearchDto })
  async createResearch(@Body() dto: CreateResearchDto) {
    const result = await this.researchService.createResearch(dto);
    return { success: true, data: result };
  }

  @Get()
  @ApiOperation({ summary: 'Get research history with pagination' })
  @ApiQuery({ name: 'page', required: false, type: Number })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiQuery({ name: 'status', required: false, type: String })
  @ApiQuery({ name: 'search', required: false, type: String })
  async getResearchHistory(@Query() query: ResearchQueryDto) {
    const result = await this.researchService.getResearchHistory(query);
    return { success: true, ...result };
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get research session by ID' })
  @ApiResponse({ status: 200, description: 'Research session details' })
  async getResearch(@Param('id') id: string) {
    const session = await this.researchService.getResearch(id);
    if (!session) {
      throw new NotFoundException('Research session not found');
    }
    return { success: true, data: session };
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Delete research session and associated data' })
  @ApiResponse({ status: 200, description: 'Research session deleted' })
  async deleteResearch(@Param('id') id: string) {
    await this.researchService.deleteResearch(id);
    return { success: true, message: 'Research session deleted' };
  }

  @Get(':id/plan')
  @ApiOperation({ summary: 'Get the research plan generated by the Planner Agent' })
  async getResearchPlan(@Param('id') id: string) {
    const plan = await this.researchService.getResearchPlan(id);
    if (!plan) {
      throw new NotFoundException('Research session not found');
    }
    return { success: true, data: plan };
  }

  @Get(':id/sources')
  @ApiOperation({ summary: 'Get sources collected for a research session' })
  async getResearchSources(@Param('id') id: string, @Query() query: SourceQueryDto) {
    const result = await this.researchService.getResearchSources(id, query);
    return { success: true, ...result };
  }

  @Get(':id/stream')
@ApiOperation({ summary: 'SSE stream of research progress events' })
async streamResearch(
  @Param('id') id: string,
  @Req() req: Request,
  @Res() res: Response,
) {
  console.log(`[SSE] Client connecting for research ID: ${id}`);

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.setHeader('X-Accel-Buffering', 'no');
  res.flushHeaders();
  res.write('retry: 3000\n\n');

  console.log(`[SSE] Headers flushed for research ID: ${id}`);

  let closed = false;
  let keepAlive: NodeJS.Timeout;
  let unsubscribe: () => void = () => {};

  const cleanup = () => {
    if (closed) return;
    console.log(`[SSE] Cleaning up connection for research ID: ${id}`);
    closed = true;
    clearInterval(keepAlive);
    unsubscribe();
  };

  const sentEventIds = new Set<string>();

  const writeEvent = (evt: ResearchProgressEvent) => {
    if (closed) {
      console.log(`[SSE] Skipping write, connection closed. event=${evt.event} id=${evt.id}`);
      return;
    }
    if (evt.id && sentEventIds.has(evt.id)) {
      console.log(`[SSE] Skipping duplicate event id=${evt.id}`);
      return;
    }

    try {
      console.log(`[SSE] Writing event for ${id}:`, {
        id: evt.id,
        event: evt.event,
        progress: evt.progress,
        message: evt.message,
      });

      if (evt.id) {
        res.write(`id: ${evt.id}\n`);
        sentEventIds.add(evt.id);
      }
      res.write(`event: ${evt.event}\n`);
      res.write(`data: ${JSON.stringify(evt)}\n\n`);
    } catch (err) {
      console.error(`[SSE] Write failed for research ID: ${id}`, err);
      cleanup();
    }
  };

  const buffer: ResearchProgressEvent[] = [];
  let backlogFlushed = false;
  const bufferingWriter = (evt: ResearchProgressEvent) => {
    if (!backlogFlushed) {
      console.log(`[SSE] Buffering live event (backlog not flushed yet): ${evt.event} id=${evt.id}`);
      buffer.push(evt);
    } else {
      writeEvent(evt);
    }
  };

  console.log(`[SSE] Subscribing to events for research ID: ${id}`);
  unsubscribe = this.eventsService.subscribe(id, bufferingWriter);
  console.log(`[SSE] Subscribed successfully for research ID: ${id}`);

  const lastEventId = req.headers['last-event-id'] as string | undefined;
  console.log(`[SSE] Last-Event-ID header: ${lastEventId ?? '(none)'}`);

  const recentEvents = lastEventId
    ? this.eventsService.getEventsSince(id, lastEventId)
    : this.eventsService.getRecentEvents(id);

  console.log(`[SSE] Found ${recentEvents.length} recent/backlog events for research ID: ${id}`);

  for (const evt of recentEvents) {
    writeEvent(evt);
  }

  backlogFlushed = true;
  console.log(`[SSE] Backlog flushed, replaying ${buffer.length} buffered live events for research ID: ${id}`);

  for (const evt of buffer) {
    writeEvent(evt);
  }
  buffer.length = 0;

  keepAlive = setInterval(() => {
    if (closed) return;
    try {
      console.log(`[SSE] Sending keepalive for research ID: ${id}`);
      res.write(': keepalive\n\n');
    } catch (err) {
      console.error(`[SSE] Keepalive write failed for research ID: ${id}`, err);
      cleanup();
    }
  }, 15000);

  res.on('close', () => {
    console.log(`[SSE] Response closed by client for research ID: ${id}`);
    cleanup();
  });

  req.on('close', () => {
    console.log(`[SSE] Request closed for research ID: ${id}`);
    cleanup();
  });
}
}
