import {
  Controller,
  Post,
  Get,
  Delete,
  Body,
  Param,
  Query,
  Res,
  NotFoundException,
  Logger,
  Req,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiQuery, ApiBody } from '@nestjs/swagger';
import { ResearchService } from './research.service';
import { CreateResearchDto } from './dto/create-research.dto';
import { ResearchQueryDto } from './dto/research-query.dto';
import { SourceQueryDto } from './dto/source-query.dto';
import { ResearchEventsService } from '../events/research-events.service';
import { ResearchProgressEvent } from '@/common/interfaces/research.interface';
import { Request, Response } from 'express';

@ApiTags('research')
@Controller('research')
export class ResearchController {
  private readonly logger = new Logger(ResearchController.name);

  constructor(
    private readonly researchService: ResearchService,
    private readonly eventsService: ResearchEventsService,
  ) {}

  @Post()
  @ApiOperation({ summary: 'Create a new research session' })
  @ApiResponse({ status: 201, description: 'Research session created and queued' })
  @ApiBody({ type: CreateResearchDto })
  async createResearch(@Body() dto: CreateResearchDto) {
    const result = await this.researchService.createResearch(dto);
    return { success: true, data: result };
  }

  @Get()
  @ApiOperation({ summary: 'Get research history with pagination' })
  @ApiQuery({ name: 'page', required: false, type: Number })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiQuery({ name: 'status', required: false, type: String })
  @ApiQuery({ name: 'search', required: false, type: String })
  async getResearchHistory(@Query() query: ResearchQueryDto) {
    const result = await this.researchService.getResearchHistory(query);
    return { success: true, ...result };
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get research session by ID' })
  @ApiResponse({ status: 200, description: 'Research session details' })
  async getResearch(@Param('id') id: string) {
    const session = await this.researchService.getResearch(id);
    if (!session) {
      throw new NotFoundException('Research session not found');
    }
    return { success: true, data: session };
  }

  @Delete(':id')
  @ApiOperation({ summary: 'Delete research session and associated data' })
  @ApiResponse({ status: 200, description: 'Research session deleted' })
  async deleteResearch(@Param('id') id: string) {
    await this.researchService.deleteResearch(id);
    return { success: true, message: 'Research session deleted' };
  }

  @Get(':id/plan')
  @ApiOperation({ summary: 'Get the research plan generated by the Planner Agent' })
  async getResearchPlan(@Param('id') id: string) {
    const plan = await this.researchService.getResearchPlan(id);
    if (!plan) {
      throw new NotFoundException('Research session not found');
    }
    return { success: true, data: plan };
  }

  @Get(':id/sources')
  @ApiOperation({ summary: 'Get sources collected for a research session' })
  async getResearchSources(@Param('id') id: string, @Query() query: SourceQueryDto) {
    const result = await this.researchService.getResearchSources(id, query);
    return { success: true, ...result };
  }

  @Get(':id/stream')
  @ApiOperation({
    summary: 'SSE stream of research progress events',
  })
  async streamResearch(
    @Param('id') id: string,
    @Req() req: Request,
    @Res() res: Response,
  ): Promise<void> {
    this.logger.log(`[SSE] Client connecting researchId=${id}`);

    res.setHeader('Content-Type', 'text/event-stream');

    res.setHeader('Cache-Control', 'no-cache, no-transform');

    res.setHeader('Connection', 'keep-alive');

    res.setHeader('X-Accel-Buffering', 'no');

    res.flushHeaders();

    res.write('retry: 3000\n\n');

    let closed = false;

    let keepAlive: NodeJS.Timeout | undefined;

    let unsubscribe: () => void = () => {};

    const cleanup = () => {
      if (closed) {
        return;
      }

      closed = true;

      if (keepAlive) {
        clearInterval(keepAlive);
      }

      unsubscribe();

      this.logger.log(`[SSE] Connection cleaned up researchId=${id}`);
    };

    const sentEventIds = new Set<string>();

    const writeEvent = (event: ResearchProgressEvent) => {
      if (closed) {
        return;
      }

      if (event.id && sentEventIds.has(event.id)) {
        return;
      }

      try {
        if (event.id) {
          res.write(`id: ${event.id}\n`);

          sentEventIds.add(event.id);
        }

        res.write(`event: ${event.event}\n`);

        res.write(`data: ${JSON.stringify(event)}\n\n`);
      } catch (error) {
        this.logger.error(`[SSE] Write failed researchId=${id}`, error);

        cleanup();
      }
    };

    unsubscribe = this.eventsService.subscribe(id, writeEvent);

    const lastEventId = req.headers['last-event-id'] as string | undefined;

    const events = lastEventId
      ? this.eventsService.getEventsSince(id, lastEventId)
      : this.eventsService.getRecentEvents(id);

    for (const event of events) {
      writeEvent(event);
    }

    keepAlive = setInterval(() => {
      if (closed) {
        return;
      }

      try {
        res.write(': keepalive\n\n');
      } catch (error) {
        this.logger.error(`[SSE] Keepalive failed researchId=${id}`, error);

        cleanup();
      }
    }, 15000);

    res.on('close', () => {
      this.logger.log(`[SSE] Response closed researchId=${id}`);

      cleanup();
    });

    req.on('close', () => {
      cleanup();
    });
  }
}
